### PR TITLE
Run make gen with new protoc

### PR DESCRIPTION
**Pull request by jacob-delgado**

### CODE REVIEW

**Comment by jacob-delgado** [comment]
No clue on why `make gen` is failing. Any thoughts @ericvn ?

**Comment by zirain** [comment]
checkout the base image of prow job?

**Comment by zirain** [comment]
maybe need https://github.com/istio/test-infra/pull/5160

**Comment by jacob-delgado** [comment]
Yeah, the common-files repo got pushed out. So we need to update that. But it needs to sync with that PR.

**Comment by jacob-delgado** [comment]
Needed by https://github.com/istio/test-infra/pull/5160

**Review by ericvn — APPROVED** [review]
This PR will fix the `gencheck` failure when https://github.com/istio/test-infra/pull/5160 merges.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
