### PR TITLE
Add missing deprecated tag for mesh fields

### PR DESCRIPTION
**Pull request by bmangoen**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
this's safe to land in 1.21

**Comment by ericvn** [comment]
@zirain The labels are usually checked at merge time, so adding a label later typically won't work. You can enter the manual '/cherry-pick' command. Note that there is a change needed in istio/istio (lint error) that would need to be cherry-picked as well.

**Pull request merged**
