### PR TITLE
delete redundant space on envoy_filter.proto

### PR DESCRIPTION
**Pull request by mstrYoda**
extra space causes yaml to be invalid

### CODE REVIEW

**Comment by howardjohn** [comment]
/ok-to-test

Can you run `make gen`?

**Comment by mstrYoda** [comment]
> /ok-to-test
> 
> Can you run `make gen`?

I ran it but there was not any change happeden on git status.

**Comment by hzxuzhonghu** [comment]
you can `make clean gen`

**Comment by mstrYoda** [comment]
> you can `make clean gen`

Thank you I made changes.

**Pull request merged**
