### PR TITLE
improve documentation for small mistaken

### PR DESCRIPTION
**Pull request by skyao**
Just correct two words.

### CODE REVIEW

**Comment by qiwzhang** [comment]
@skyao  after you make proto file changes, you need to Re-run ./scripts/generate-protos.sh

**Comment by skyao** [comment]
@qiwzhang Please help to check what happened. I just changed some comments, why build failed?

**Comment by skyao** [comment]
@qiwzhang Help review, another small documentation updated.

**Comment by qiwzhang** [comment]
@skyao after you make proto file changes, you need to Re-run ./scripts/generate-protos.sh
We also check in generated documents.

**Comment by skyao** [comment]
@qiwzhang I don't have env to run this script because of gcr is blocked by gfw. So, please help to correct the documentation as list in this PR (just three words).

I will close this issue.

**Pull request closed without merging**
