### PR TITLE
add an field to avoid interpreting the hosts on dr and vs

### PR DESCRIPTION
**Pull request by Patrick0308**
See https://github.com/istio/istio/issues/36864

Adding an option on virtual service's spec. if the field is true, istio will be not resolve short name to FQDN. Denstation rule is the same.

### CODE REVIEW

**Comment by Patrick0308** [comment]
To run `make gen` fail on m1 Mac.  
```
❯ make gen
./clean.sh
./gen.sh
Syncing ./networking/v1beta1/destination_rule.proto from networking/v1alpha3/destination_rule.proto
Syncing ./networking/v1beta1/gateway.proto from networking/v1alpha3/gateway.proto
Syncing ./networking/v1beta1/service_entry.proto from networking/v1alpha3/service_entry.proto
Syncing ./networking/v1beta1/sidecar.proto from networking/v1alpha3/sidecar.proto
Syncing ./networking/v1beta1/virtual_service.proto from networking/v1alpha3/virtual_service.proto
Syncing ./networking/v1beta1/workload_entry.proto from networking/v1alpha3/workload_entry.proto
Syncing ./networking/v1beta1/workload_group.proto from networking/v1alpha3/workload_group.proto
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Failure: plugin gogofast: signal: segmentation fault; signal: segmentation fault; signal: segmentation fault; signal: segmentation fault; signal: segmentation fault; signal: segmentation fault; signal: segmentation fault; signal: segmentation fault; signal: segmentation fault; signal: segmentation fault.
make[1]: *** [Makefile.core.mk:37: gen-proto] Error 1
make: *** [gen] Error 2
```
It looks like it's caused by a bug in qemu. See https://github.com/docker/for-mac/issues/5123#issuecomment-784992589

**Comment by Patrick0308** [comment]
@howardjohn @hzxuzhonghu. Hey guys, I want to know what's your opinion about this.

**Comment by louiscryan** [comment]
What is the purpose of this change? I get that host interpretation can be complex - see DNS - but do we have a reason not to follow the DNS spec for host strings?

**Comment by Patrick0308** [comment]
@louiscryan Pls see https://github.com/istio/istio/issues/36864. When the service host is the k8s service host, the short name interpreted to FQDN. It's ok. However, if the host is for service entry, the interpretation is unwarranted.

**Pull request closed without merging**
