### PR TITLE
Cherrypicking https://github.com/istio/api/pull/467

### PR DESCRIPTION
**Pull request by incfly**
This is needed if we want to remove the authn policy inferences. Currently  this #467 is only available in istio/api master branch.

### CODE REVIEW

**Comment by incfly** [comment]
I use `git cherry-pick 170445541e5b5a1515b52c9c9596570220679a27` to generate this PR,
@hklai @diemtvu PTAL, thx!

**Comment by incfly** [comment]
To keep things tracked, this is for https://github.com/istio/istio/issues/5059

**Comment by ldemailly** [comment]
it missed 3 notifications, seems unlikely no ?
(original + 2 retests)

**Pull request merged**
