### PR TITLE
Add Datadog tracing to proxy config (release-1.1)

### PR DESCRIPTION
**Pull request by cgilmour**
This was already submitted and accepted on `master`, but due to other changes, needs to be resubmitted on `release-1.1`

Signed-off-by: Caleb Gilmour <caleb.gilmour@datadoghq.com>

### CODE REVIEW

**Comment by duderino** [comment]
@rshriram @douglas-reid you guys already lgtm'd this on against master.  Could you lgtm it for the release-1.1 branch too?   The master PR for your reference:  https://github.com/istio/api/pull/797

@cgilmour given how close we are to cutting 1.1, I'd like to merge this immediately after so it would ship in 1.1.1.

**Comment by cgilmour** [comment]
Sounds good, @duderino

**Comment by rshriram** [comment]
is this feature in istio/istio release-1.1 branch already?

**Comment by cgilmour** [comment]
No, it's on master from an earlier PR.

**Comment by cgilmour** [comment]
Can I get an OK on this? It's needed to produce a PR against istio `release-1.1` branch also.
(A rebase of istio/istio#11855)

**Comment by rshriram** [comment]
Ah so you want this to go into release-1.1 ? it was not immediately clear from "but due to other changes, needs to be resubmitted on release-1.1" that this was a backport as well. Thats why I was asking if this was in istio/istio or not. I am not sure if its too late to get into 1.1 as our feature freeze happened a month ago before this PR. But if the change is straightforward, we might be able to get it in.

**Comment by rshriram** [comment]
thoughts @duderino ? this is similar to lightstep and such, which landed a while ago

**Comment by rshriram** [comment]
nm.. I see @duderino 's response above

**Comment by cgilmour** [comment]
Thanks!

**Pull request merged**
