### PR TITLE
Missing quote in match example

### PR DESCRIPTION
**Pull request by esnible**
Resolves https://github.com/istio/api/issues/927

### CODE REVIEW

**Comment by esnible** [comment]
@geeknoid any idea why this is failing presubmit?

**Comment by esnible** [comment]
@geeknoid any idea why this is failing presubmit?

**Comment by linsun** [comment]
here is the failing log, still not sure why it failed tho @geeknoid @howardjohn @fpesce.  It certainly complained about the change from PR.

```
I0605 21:16:24.752] --- a/policy/v1beta1/cfg.pb.go
I0605 21:16:24.752] +++ b/policy/v1beta1/cfg.pb.go
I0605 21:16:24.752] @@ -306,7 +306,7 @@ type Rule struct {
I0605 21:16:24.752]  	//
I0605 21:16:24.752]  	// * an empty match evaluates to `true`
I0605 21:16:24.752]  	// * `true`, a boolean literal; a rule with this match will always be executed
I0605 21:16:24.752] -	// * `match(destination.service.host, "ratings.*)` selects any request targeting a service whose
I0605 21:16:24.753] +	// * `match(destination.service.host, "ratings.*")` selects any request targeting a service whose
I0605 21:16:24.753]  	// name starts with "ratings"
I0605 21:16:24.753]  	// * `attr1 == "20" && attr2 == "30"` logical AND, OR, and NOT are also available
I0605 21:16:24.753]  	Match string `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
I0605 21:16:24.753] diff --git a/policy/v1beta1/istio.policy.v1beta1.pb.html b/policy/v1beta1/istio.policy.v1beta1.pb.html
I0605 21:16:24.753] index eae6280..6b3dd9b 100644
I0605 21:16:24.753] --- a/policy/v1beta1/istio.policy.v1beta1.pb.html
I0605 21:16:24.753] +++ b/policy/v1beta1/istio.policy.v1beta1.pb.html
I0605 21:16:24.753] @@ -1115,7 +1115,7 @@ if the match evaluates to true.</p>
I0605 21:16:24.753]  <ul>
I0605 21:16:24.753]  <li>an empty match evaluates to <code>true</code></li>
I0605 21:16:24.754]  <li><code>true</code>, a boolean literal; a rule with this match will always be executed</li>
I0605 21:16:24.754] -<li><code>match(destination.service.host, &quot;ratings.*)</code> selects any request targeting a service whose
I0605 21:16:24.754] +<li><code>match(destination.service.host, &quot;ratings.*&quot;)</code> selects any request targeting a service whose
I0605 21:16:24.754]  name starts with &ldquo;ratings&rdquo;</li>
I0605 21:16:24.754]  <li><code>attr1 == &quot;20&quot; &amp;&amp; attr2 == &quot;30&quot;</code> logical AND, OR, and NOT are also available</li>
I0605 21:16:24.754]  </ul>
I0605 21:16:24.754] Repo has unstaged changes. Re-run ./scripts/generate-protos.sh or make proto-commit
E0605 21:16:24.754] Build failed
I0605 21:16:24.754] process 580 exited with code 1 after 1.6m
E0605 21:16:24.755] FAIL: api-presubmit
```

**Comment by howardjohn** [comment]
@esnible 

> You need to run "make" before submitting the PR so that the (unforutnately) checked in generated files are correctly updated. Doing so will fix the CI failures.

From Martin on https://github.com/istio/api/pull/795#issuecomment-463309772

**Comment by howardjohn** [comment]
@esnible you somehow picked up some other changes in here, maybe a merge gone wrong

**Comment by esnible** [comment]
@howardjohn I rebased and pushed, causing Git to think I had changed 46 files.  I changed the target away from `master`, then back, using the Github web UI.  Seems to have fixed the problem.  Github now shows exactly the intended changes, but the CLA fell off.  I'll need a Googler to restore it manually.

**Comment by esnible** [comment]
@linsun After my rebase your /lgtm fell off.

**Pull request merged**
