### PR TITLE
Update prototool.

### PR DESCRIPTION
**Pull request by jeffmendoza**
Change to download a release instead of building from source. Run `prototool commit` with new version to get updated proto.lock

New version contains new flags wanted in #707.

If this looks good, I need access to `gcr.io/istio-testing` to push docker images before tests will pass.

### CODE REVIEW

**Comment by ozevren** [comment]
looks good.

**Comment by jeffmendoza** [comment]
@costinm Could you give me temp access to push to `gcr.io/istio-testing`? Thanks.

**Comment by ozevren** [comment]
@utka, any chance we can get some help with updating the testing image?

**Comment by utka** [comment]
Sure, I can give access to istio-testing to @jeffmendoza to push images

**Comment by jeffmendoza** [comment]
Images pushed and Prow is passing. @ozevren can you retrigger Circle?

**Comment by ozevren** [comment]
Done

**Comment by jeffmendoza** [comment]
@ozevren Tests pass, PTAL

**Pull request merged**
