### PR TITLE
fix httpbin.com -> example.com

### PR DESCRIPTION
**Pull request by xichengliudui**
ref: https://github.com/istio/istio.io/pull/10722

### CODE REVIEW

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
Donot see the necessity of changing it, it is just an example

**Comment by howardjohn** [comment]
ideal is probably example.com - it's specifically meant for cases like this

**Comment by xichengliudui** [comment]
> 

the `httpbin.com` domain name does not exist and using it can be confusing for beginners，`httpbin.org` exists

**Comment by xichengliudui** [comment]
do i need to close or update to `example.com`?

**Comment by ericvn** [comment]
> do i need to close or update to `example.com`?

I think updating to example.com would solve the issue of using a link that isn't found, and still imply to a user that they should change it.

**Review by howardjohn — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
