### PR TITLE
Fix typo in peer authentication docs

### PR DESCRIPTION
**Pull request by peterj**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
lgtm, please run `make gen` though

**Review by smawson — APPROVED** [review]

**Review by smawson — CHANGES_REQUESTED** [review]
Oops make sure to run make gen

**Comment by peterj** [comment]
@smawson looks like the error is because of the release notes label (or the lack of it :)). Does a typo fix need release notes?

**Review by smawson — APPROVED** [review]

**Pull request merged**
