### PR TITLE
Disable circuit breaking by default

### PR DESCRIPTION
**Pull request by dgn**
This updates ConnectionPoolSettings comments according to https://github.com/istio/istio/pull/17346

### CODE REVIEW

**Comment by howardjohn** [comment]
Somewhat related, would be useful is if we could provide a default
destination rule that is merged, the  regardless of what defaults we set
folks could set global defaults. For cases where a central team controls
the istio config it's less useful, but for other setups where application
teams are configuring istio it would allow admins to set their own defaults

**Comment by Stono** [comment]
I'm in favour of removing default configuration like this.  The defaults caught us out too.

Out of curiosity, why are things like `http2MaxRequests` being set to int32 max (2^32-1) rather than simply disabled by default?

**Comment by dgn** [comment]
> I'm in favour of removing default configuration like this. The defaults caught us out too.
> 
> Out of curiosity, why are things like `http2MaxRequests` being set to int32 max (2^32-1) rather than simply disabled by default?

Envoy doesn't have an option to disable connection pool limits, you can only set really high limits to achieve a similar result, see this FAQ entry: https://www.envoyproxy.io/docs/envoy/latest/faq/disable_circuit_breaking#is-there-a-way-to-disable-circuit-breaking

**Comment by jwendell** [comment]
Code changes were merged in istio/istio. Can this be merged too?

**Pull request merged**
