### PR TITLE
Add regex rewrite

### PR DESCRIPTION
**Pull request by SpecialYang**
In our gateway case, we definitely need this awesome feature to meet so many path routes. Maybe `EnvoyFilter` can support regex rewrite for data plane. But we are tired to name these routes that require regular rewriting. Only if we pick meaningful names for these routes, `EnvoyFilter` can match these route names and apply regex rewrite policy. Adding regex rewrite api for rewrite in `HTTPRoute` is the easy way to fix this case. I think someone needs this feature like me.

Based on this pr https://github.com/istio/api/pull/1566, introduce RegexMatchAndSubstitute which may be used in the future for similar cases.
@howardjohn @hzxuzhonghu 

Fixes https://github.com/istio/istio/issues/22290 and https://github.com/istio/istio/issues/24172.

### CODE REVIEW

**Comment by SpecialYang** [comment]
@googlebot I consent

**Comment by howardjohn** [comment]
I am personally fine with this, but wanted to echo @costinm concern: https://github.com/istio/api/pull/1566#issuecomment-767631005

> At least we should bounce the idea with the K8S Services WG - and the other projects planning to support the K8S APIs.
> I assume since this didn't make it to 1.9 we can afford few weeks to discuss with the relevant WGs.

**Comment by hzxuzhonghu** [comment]
lgtm
>At least we should bounce the idea with the K8S Services WG

Is this the service-apis?

**Comment by SpecialYang** [comment]
> I am personally fine with this, but wanted to echo @costinm concern: [#1566 (comment)](https://github.com/istio/api/pull/1566#issuecomment-767631005)
> 
> > At least we should bounce the idea with the K8S Services WG - and the other projects planning to support the K8S APIs.
> > I assume since this didn't make it to 1.9 we can afford few weeks to discuss with the relevant WGs.

Same question. Why is it related to service APIs?  

The regex rewrite policy for uri is basic feature in most gateway products. Our gateway envoy get runtime configs from istiod via xds protocol. We must apply many `EnvoyFilter` configs and pick up meaningful names for target routes. We want an easy way just like configuring the regex rewrite policy directly in HTTPRoute, which is clear.

As I know, current istiod use RE2 for all regex match cases. I think we can also use it in regex rewrite until istiod support different regex styles.

I'm sure many users will look forward to this feature. Thanks.

**Comment by gengleilei** [comment]
Great. adding regular-based rewriting is necessary.

**Comment by SpecialYang** [comment]
> > I am personally fine with this, but wanted to echo @costinm concern: [#1566 (comment)](https://github.com/istio/api/pull/1566#issuecomment-767631005)
> > > At least we should bounce the idea with the K8S Services WG - and the other projects planning to support the K8S APIs.
> > > I assume since this didn't make it to 1.9 we can afford few weeks to discuss with the relevant WGs.
> 
> Same question. Why is it related to service APIs?
> 
> The regex rewrite policy for uri is basic feature in most gateway products. Our gateway envoy get runtime configs from istiod via xds protocol. We must apply many `EnvoyFilter` configs and pick up meaningful names for target routes. We want an easy way just like configuring the regex rewrite policy directly in HTTPRoute, which is clear.
> 
> As I know, current istiod use RE2 for all regex match cases. I think we can also use it in regex rewrite until istiod support different regex styles.
> 
> I'm sure many users will look forward to this feature. Thanks.

@howardjohn @costinm PTAL. Thanks.

**Comment by sugelalin** [comment]
Is this done? i desire this function!

**Comment by SpecialYang** [comment]
> Is this done? i desire this function!
cc @howardjohn @hzxuzhonghu @costinm  Is there any latest feedback here?

**Comment by kmai** [comment]
@howardjohn will this ever see the light? I opened https://github.com/istio/istio/issues/22290 one year and a half ago :(

**Comment by fatedier** [comment]
@SpecialYang @howardjohn @hzxuzhonghu Anyone working on this PR?

**Comment by SpecialYang** [comment]
> @SpecialYang @howardjohn @hzxuzhonghu Anyone working on this PR?

I am working on this. But the community seems don't accept this api change yet. We add this feature in our internal version of istio and run in production. Hope community can rethink about this very common feature to fix this long-alive issue https://github.com/istio/istio/issues/22290.

**Comment by howardjohn** [comment]
I would recommend giving feedback on https://github.com/kubernetes-sigs/gateway-api/pull/731, as Istio will implement this API.

**Comment by fatedier** [comment]
> I would recommend giving feedback on [kubernetes-sigs/gateway-api#731](https://github.com/kubernetes-sigs/gateway-api/pull/731), as Istio will implement this API.

What's the relationship between gateway-api and istio virtual service? Do you mean that virtualservice would not implement complicated features, users who need these features should use gateway-api instead?

**Comment by howardjohn** [comment]
> What's the relationship between gateway-api and istio virtual service? Do you mean that virtualservice would not implement complicated features, users who need these features should use gateway-api instead?

The gateway-api can be seen as the next evolution of the Istio APIs (in the future), with a common API shared by many proxy implementations. By getting this feature into that API it would make it an obvious choice to _also_ add it to VirtualService

**Comment by dm3ch** [comment]
@SpecialYang @howardjohn I'm very sorry for mentioning, but what the current status?

The process of discussion/implementing this feature seems not transparent at all.
Is this PR not merged due to conflicts or there's some internal maintainers decision that this wouldn't be merged due to some ideological considerations?

**Comment by ramaraochavali** [comment]
@howardjohn Is the necessary gateway api fields been added? If not should we just go ahead and add this support. This seems pretty reasonable request and some of our service owners are also asking for this feature.

**Comment by gabomarf** [comment]
@SpecialYang , @istio-policy-bot , @googlebot . What happened in the end with this pull, are they going to implement it or not?

**Comment by gabomarf** [comment]
Can you review this pull request, please?
@dcberg
@duderino 
@linsun 
@louiscryan 
@nrjpoddar 
@smawson 
@istio/technical-oversight-committee

**Comment by gabomarf** [comment]
Can you review this PR, please ?

@dcberg
@duderino
@linsun
@louiscryan
@nrjpoddar
@smawson
@istio/technical-oversight-committee

**Comment by gabomarf** [comment]
Can you review this PR, please ?

@dcberg
@duderino
@linsun
@louiscryan
@nrjpoddar
@smawson
@istio/technical-oversight-committee

**Comment by timonwong** [comment]
Seems this is completed in #2753

**Pull request closed without merging**
