### PR TITLE
Add loadBalancerClass to the serviceSpec of the Operator

### PR DESCRIPTION
**Pull request by karanrn**
Adds `loadBalancerClass` to the `ServiceSpec` of the Operator proto to support the field for the gateways or any services deployed through `istioctl` 

Issue: https://github.com/istio/istio/issues/48360

### CODE REVIEW

**Comment by karanrn** [comment]
@zirain Can you please review?

**Review by zirain — APPROVED** [review]
LGTM

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
