### PR TITLE
fix destination rule ttl mismatched type

### PR DESCRIPTION
**Pull request by kentchenjh**
related to #1269

### CODE REVIEW

**Comment by rshriram** [comment]
You will have to send a PR to istio/istio to ensure that the ttl is properly processed. Removing the gogo stdduration will require us to fix the go structs in pilot code that sets up the TTL

**Comment by rshriram** [comment]
Once you send that PR, happy to approve this as well.

**Comment by kentchenjh** [comment]
already send a PR, 
check https://github.com/istio/istio/pull/21101

**Pull request merged**
