### PR TITLE
Remove defaultRevision

### PR DESCRIPTION
**Pull request by jaymiracola**
Setting `defaultRevision` as described does not function as intended or described (not boolean). It should be set as seen below. 
```
values:
  defaultRevision: 1-16
```

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

### CODE REVIEW

**Comment by linsun** [comment]
@richardwxn @ostromart can you comment on this pls?  Seems safe to remove?

**Comment by linsun** [comment]
Pinged @richardwxn @ostromart on slack. I'm leaning towards removing it as it doesn't work any way.

**Review by howardjohn — CHANGES_REQUESTED** [review]
Not sure what you mean it does nothing?

```
$ istioctl manifest generate --set values.defaultRevision=foo > /tmp/dr
$ istioctl manifest generate  > /tmp/no-dr
$ diff /tmp/dr /tmp/no-dr
8874,8909d8873
< apiVersion: admissionregistration.k8s.io/v1
< kind: ValidatingWebhookConfiguration
< metadata:
<   labels:
<     app: istiod
<     istio: istiod
<     istio.io/rev: foo
<     release: istio
<   name: istiod-default-validator
...
``

**Comment by jaymiracola** [comment]
Ill elaborate to hopefully clear it up. The following is how the [doc suggests](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/) `defaultRevision` is set. 
```
spec:
  hub: gcr.io/istio-release
  tag: 1.16.3
  revision: 1-16
  profile: minimal
  defaultRevision: true
```

My first comment is how it needs to be applied to be set.

**Comment by howardjohn** [comment]
I agree that doc is wrong. Its not supposed to be a bool but rather the name of the default revision

**Comment by jaymiracola** [comment]
That too. My point is more `spec.defaultRevision` does nothing. While `spec.values.defaultRevision` works.

**Review by howardjohn — APPROVED** [review]
Sorry I misunderstood. This LGTM. Thanks!

Youll need to run `make gen` though

**Comment by linsun** [comment]
@jaymiracola - I didn't hear from @richardwxn @ostromart. I'm good with removing it.

Could you please sync to latest code base, run make gen as John mentioned and get all the tests passing?

**Review by linsun — COMMENTED** [review]
LGTM, okay to approve after tests passing. feel free to ping me

**Comment by linsun** [comment]
Also noted that your CLA is missing, you can sign as corporate if you want, @jaymiracola

**Comment by linsun** [comment]
@jaymiracola let me know if you have time to work on rebase. If not, we can have someone else pick it up.

cc @peterj

**Review by linsun — APPROVED** [review]

**Comment by zirain** [comment]
should this be part of 1.21?

**Comment by hanxiaop** [comment]
I think it can be. 

/cherry-pick release-1.21

**Pull request merged**
