### PR TITLE
fix EnvoyFilter docs

### PR DESCRIPTION
**Pull request by theganyo**
See issue: https://github.com/istio/istio/issues/12313

### CODE REVIEW

**Comment by geeknoid** [comment]
@theganyo Please rebase and repush this PR. When changing a proro, you need to do "make" locally and check in any file that's been modified by the build.

Thanks.

**Comment by linsun** [comment]
/approve
/lgtm
some of yours are coverey by https://github.com/istio/api/pull/865

**Comment by theganyo** [comment]
Merge went weird. Closing, will open new PR.

**Pull request closed without merging**
