### PR TITLE
Fix for some text that went missing

### PR DESCRIPTION
**Pull request by ericvn**
Noted in slack that some text was missing on istio.io. The file is copied from here.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by smawson — APPROVED** [review]
Any idea why the generated docs disappeared?

**Comment by howardjohn** [comment]
The issue is the newline between the `package` and the comment.

**Comment by smawson** [comment]
Whitespace is semantically important, wonderful :)

**Pull request merged**
