### PR TITLE
Add pathTemplates and notPathTemplates to AuthorizationPolicy

### PR DESCRIPTION
**Pull request by jaellio**
Increases templating support for positive and negative path mathching.

Part of https://github.com/istio/istio/issues/16585

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
should we deprecate paths and notPaths

**Comment by howardjohn** [comment]
I don't think we should make a new field but rather us 'path'. there shouldn't be any compatibility concerns as {} is not a valid character in a real path. all the discussions about what we support in templates is constraint inside {}

**Comment by jaellio** [comment]
Closing in favor of https://github.com/istio/istio/pull/50365

**Pull request closed without merging**
