### PR TITLE
Fix a tiny typo in virtualservice documentation

### PR DESCRIPTION
**Pull request by morphalus**
specfied -> specified

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by Chen-Xintong** [comment]
@morphalus Please sign the CLA.

**Comment by morphalus** [comment]
> @morphalus Please sign the CLA.

CLA has been signed

**Review by kfaseela — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Pull request merged**
