### PR TITLE
bump k8s hpa api mirrored in operator api to v2beta2

### PR DESCRIPTION
**Pull request by richardwxn**
for https://github.com/istio/istio/issues/32005

v2beta1 was deprecated in 1.19 and to be removed in 1.25

### CODE REVIEW

**Comment by richardwxn** [comment]
@howardjohn PTAL

**Comment by linsun** [comment]
changes look reasonable to me.

**Comment by howardjohn** [comment]
Waiting for https://github.com/istio/istio/pull/37872#issuecomment-1068525287 to make sure it works before merging

**Comment by howardjohn** [comment]
Waiting for https://github.com/istio/istio/pull/37872#issuecomment-1068525287 to make sure it works before merging

**Review by howardjohn — APPROVED** [review]

**Comment by richardwxn** [comment]
@ericvn @jacob-delgado can you PTAL as it is a release blocker for 1.14

**Review by ostromart — APPROVED** [review]

**Pull request merged**
