### PR TITLE
fix(requestauthentication): typo

### PR DESCRIPTION
**Pull request by scraly**
Fix a typo in the requestauthenticate page.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by shamsher31** [comment]
Why is this PR https://github.com/istio/api/pull/1474 closed? It's already reviewed and approved.

I see commits from 2 different ids and that is why it's not able to verify consent.

**Comment by scraly** [comment]
I opened another one 😉

Le mer. 1 juil. 2020 à 07:49, Shamsher Ansari <notifications@github.com> a
écrit :

**Comment by scraly** [comment]
I closed #1474 because I commited with two differents users, a mistake, sorry.
So the good one is this PR, thanks.

**Comment by scraly** [comment]
Is it possible to review this simple PR please? :-) 
Thanks

**Comment by scraly** [comment]
Any news about this PR?
Thanks

**Review by shamsher31 — APPROVED** [review]

**Comment by brian-avery** [comment]
This looks like this has since been fixed in https://github.com/istio/api/pull/1657.

**Pull request closed without merging**
