### PR TITLE
Fix typo Authorizaion  to Authorization

### PR DESCRIPTION
**Pull request by zioproto**
Related to https://github.com/istio/istio.io/pull/13753

### CODE REVIEW

**Comment by kfaseela** [comment]
@ericvn I was wondering why `make gen` did not update this file, when I modified the .proto https://github.com/istio/api/pull/2894

**Review by howardjohn — COMMENTED** [review]
Unfortunately need to change the .proto file then run `make gen`. Looks good though

**Comment by ericvn** [comment]
`make gen` and other tests not run

**Comment by ericvn** [comment]
Follow John's instructions above and add the commit and the tests should hopefully pass.

**Comment by ericvn** [comment]
Add release-notes-none flag since not required for a spelling change.

**Comment by zioproto** [comment]
I committed the change to the `.proto` file

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
