### PR TITLE
Adding python output

### PR DESCRIPTION
**Pull request by sepulworld**
* Generate python outputs to python/istio_api
* setup.py (could be used with Circle CI with right commands to send to pypi)
* Updated readme

### CODE REVIEW

**Comment by sepulworld** [comment]
I signed it!

**Comment by kyessenov** [comment]
Thank you for adding python bindings! I think this looks fine to me, it's in the vein of auto-generating all the API artifacts. What do you think @douglas-reid @geeknoid @rshriram ?

**Comment by douglas-reid** [comment]
Cool!  The intent, as I understand it, of this repo is to house generated artifacts for the protos, so it makes sense to me to add it.

**Comment by sepulworld** [comment]
Great! Thanks for merging in. I think the next steps would be:

1. Copy in docs to python/istio_api/
2. Integrate with CircleCI to publish a pip package for consumption though [pypi](https://pypi.python.org/pypi)

I'll submit a new PR for this

**Pull request merged**
