### PR TITLE
mixer: allow setting empty header if necessary

### PR DESCRIPTION
**Pull request by kyessenov**
Adding an operation to set a header to an empty value.
See https://github.com/istio/istio/issues/10801

Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by linsun** [comment]
what would be the scenario to set empty header?

**Comment by geeknoid** [comment]
@kyessenov Do we still need this PR?

**Comment by geeknoid** [comment]
Please reopen if this is still needed.

**Pull request closed without merging**
