### PR TITLE
Add release 1.7 release lock

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by jwendell** [comment]
Please advice. I copied 1.6 files and ran the script, which generates the `status` file, which is the same as in 1.6. Is that right?

**Comment by JimmyCYJ** [comment]
@jasonwzm could you help to take a look?

**Comment by jasonwzm** [comment]
@jwendell Can you follow https://github.com/istio/api/blob/master/scripts/check-release-locks.md? Basically we copy the status file in the release-1.7 branch into release-1.7 folder on master branch.

**Comment by jwendell** [comment]
@jasonwzm I did that.

**Comment by jwendell** [comment]
@rshriram can you take a look at this?

**Comment by jwendell** [comment]
I've rebased this against master
Here's what I did:
- checkout to 1.7
- rm proto.lock && protolock init && mv proto.lock xuxa
- commented rm line on check-release-notes.sh && run it
- checkout to master
- mv xuxa releaselocks/release-1.7/proto.lock
- mv status releaselocks/release-1.7/proto.lock.status
- commit & push to this pr

`make release-lock-status` is failing both for me locally and on this pr. What's missing?

**Pull request closed without merging**
