### PR TITLE
Use proper destination field type in DestinationWeight

### PR DESCRIPTION
**Pull request by rshriram**
From `string destination` to `IstioService destination`

### CODE REVIEW

**Comment by sebastienvas** [comment]
Is this for 0.2 ?

**Comment by sebastienvas** [comment]
Anyone making  a change to API, need to do the following update:
mixer
mixerclient -> proxy -> pilot
 
Note that pilot also direclty depends on api

**Comment by kyessenov** [comment]
This change only affects pilot. I propose we break this repo apart if the requirement now is to have a single SHA across istio.

**Comment by ldemailly** [comment]
the basic sanity requirement is indeed to have all internal repos releasing the same sha/version/tag

https://github.com/istio/istio/issues/724 should eventually document the complete list and ideally we'd have a simple script/tool to update it (or integrate it with the update deps bot)

**Pull request merged**
