### PR TITLE
Escape underscores in Gateway doc

### PR DESCRIPTION
**Pull request by alitoufighi**
I guess you're using some Markdown parser at the end to generate the final page.
Currently it looks like this [here](https://istio.io/latest/docs/reference/config/networking/gateway/):
image

### CODE REVIEW

**Comment by alitoufighi** [comment]
@googlebot I signed it!

**Comment by smawson** [comment]
I only see changes to generated files, this needs to be fixed in the generator.

**Comment by alitoufighi** [comment]
Haha. I screwed everything up then came back to life.
@smawson ping

**Comment by smawson** [comment]
I still only see changes to generated files. Did you modify the generator?

**Comment by shamsher31** [comment]
@alitoufighi Thanks for your contribution.

You should only change `.proto` file and then run `make gen`.

This is fixed in `master` https://github.com/istio/api/pull/1610

**Comment by alitoufighi** [comment]
Thanks guys, I unfortunately wasn't aware about the way you generate the docs.

**Comment by shamsher31** [comment]
No problem, this is sometimes confusing. You can refer https://github.com/istio/api#updating for more details.

I have cherry-picked it for  `1.7` https://github.com/istio/api/pull/1684

**Pull request closed without merging**
