### PR TITLE
add new pattern SERVICE_NAME variable for stat prefix

### PR DESCRIPTION
**Pull request by Ferdudas97**
add new pattern SERVICE_NAME variable for stat prefix

### CODE REVIEW

**Comment by peterj** [comment]
@Ferdudas97 make sure you run `make gen` and include the generated files in the PR. That will take care of the `gencheck_api` error. 

I am not sure whether this change should include a release note or not though (@zirain ?).

**Comment by zirain** [comment]
link to https://github.com/istio/istio/pull/52179, there's a release notes, so we didn't need another one.

**Review by zirain — APPROVED** [review]
LGTM, cc @ramaraochavali

**Review by ramaraochavali — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]
thanks!

**Pull request merged**
