### PR TITLE
update api code owners to the right set of people

### PR DESCRIPTION
**Pull request by rshriram**

### CODE REVIEW

**Comment by duderino** [comment]
I think the people who are being removed should get a chance to review this PR.

@andraxylia @costinm @diemtvu @GregHanson

**Comment by kyessenov** [comment]
What makes an owner of the API? I'd like to get a chance to review mixer-related APIs, for example.

**Comment by howardjohn** [comment]
+1, what makes someone the "right set of people"?

**Comment by costinm** [comment]
Seems a bit arbitrary - is this based on a ToC decision ? Or what was the criteria ?

**Comment by costinm** [comment]
I can understand having only ToC members - since they need to approve the API changes, but it doesn't seem to be the case ( unless toc membership changed )

**Comment by duderino** [comment]
I've added an item to discuss this in the next TOC meeting on 8/9.

**Comment by rshriram** [comment]
This was the list IIRC before the code owners. I for sure remember louisryan and sven being part of the owners for approving API prs. So I am simply trying to restore the old list. let me check with the old owners to make sure I got the names right.

**Comment by rshriram** [comment]
Here is the kitchen sink from a few weeks ago

```
# Please add your github ID alphabetically.
reviewers:
  - andraxylia
  - costinm
  - diemtvu
  - frankbu
  - geeknoid
  - GregHanson
  - hklai
  - kyessenov
  - mandarjog
  - ozevren
  - qiwzhang
  - rshriram
  - utka
  - wattli
approvers:
  - andraxylia
  - costinm
  - diemtvu
  - frankbu
  - geeknoid
  - GregHanson
  - hklai
  - kyessenov
  - mandarjog
  - ozevren
  - qiwzhang
  - rshriram
  - utka
  - wattli
```

hmm. I guess this matches the current codeowners..

**Comment by hzxuzhonghu** [comment]
Maybe should also add owners to subdirectory, like networking, mixer, security, etc.

**Comment by costinm** [comment]
To be clear: I don't mind if the list includes TOC members and nobody else,
with 2 or 3 +1 required for approval.

There are far too many API changes without sufficient TOC review and having
a high bar for approval in API would be highly valuable.

**Comment by costinm** [comment]
Or even better: with a majority of TOC required for approval :-)

That would really make the APIs stable !

**Comment by kyessenov** [comment]
This whole CODEOWNERS change is not proving its utility. Why can't we have separate reviewers and approvers now?

**Pull request closed without merging**
