### PR TITLE
Switch to the build-tools image

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by howardjohn** [comment]
also see - no codeowners required

**Comment by geeknoid** [comment]
Yeah, I'm working on the lint rule. The build-tools and api-build-tools container weren't lining up.

As for code owners, it's because I'm an admin and GitHub seems to consider that sufficient I think.  The permission is set in the GitHub UI to demand CODEOWNERS reviews for this repo. But we don't have  the "enforce branch protection for admins" option on at the moment. We can turn  that on globally  once test-infra is using CODEOWNERS. Coming soon.

**Comment by geeknoid** [comment]
See https://github.com/istio/api/pull/1025

**Pull request merged**
