### PR TITLE
#939: Changing the documentation to the format 'namespace/name' (without leading slash)

### PR DESCRIPTION
**Pull request by kaushikchaubal**

### CODE REVIEW

**Comment by kaushikchaubal** [comment]
I signed it!

**Comment by jeffmendoza** [comment]
@kaushikchaubal Looks like the error is:

```
Repo has unstaged changes. Re-run ./scripts/generate-protos.sh or make proto-commit
```

Try that out.

**Comment by jeffmendoza** [comment]
You'll also need `make clean generate` as described here: https://github.com/istio/api/blob/master/README.md#updating

**Comment by kaushikchaubal** [comment]
@jeffmendoza - i have run the following commands and pushed as per your comment:
```
make proto-commit
make clean generate
```

**Pull request merged**
