### PR TITLE
fix gateways typo

### PR DESCRIPTION
**Pull request by boredabdel**

### CODE REVIEW

**Comment by boredabdel** [comment]
@googlebot I fixed it

**Comment by boredabdel** [comment]
@googlebot I fixed it.

**Comment by shamsher31** [comment]
@boredabdel I think you used different GitHub id's to commit and sign CLA.

**Comment by boredabdel** [comment]
@shamsher31 yes i made a mistake by not setting my email to the correct one. Will try again to get it ok's by the Google bot.

**Comment by boredabdel** [comment]
@googlebot I fixed it.

**Comment by boredabdel** [comment]
Was using the wrong account, will close this one and open a new one!

**Pull request closed without merging**
