### PR TITLE
redirect shoud be child filed of HTTPRoute

### PR DESCRIPTION
**Pull request by idouba**

### CODE REVIEW

**Comment by andraxylia** [comment]
Please fix circleci failure.

**Comment by andraxylia** [comment]
Repo has unstaged changes. Re-run ./scripts/generate-protos.sh

**Comment by idouba** [comment]
> Repo has unstaged changes. Re-run ./scripts/generate-protos.sh

@andraxylia  Done, pls help review it , thanks.

**Comment by geeknoid** [comment]
@andraxylia Are we good to merge this?

If so, can you create a cherry pick to the release-1.1 branch?

Thanks.

**Pull request closed without merging**
