### PR TITLE
Hide dns certificate management from docs

### PR DESCRIPTION
**Pull request by howardjohn**
Aligns with https://github.com/istio/istio.io/pull/11369

### CODE REVIEW

**Comment by linsun** [comment]
Do we need a release note for this in case anyone is using this?

**Comment by howardjohn** [comment]
We aren't removing it, just hiding it

**Comment by hzxuzhonghu** [comment]
I think we need to deprecate it, donot think any user is using this.

**Comment by linsun** [comment]
approval pending on resolving merge conflict...

**Review by ericvn — APPROVED** [review]
LGTM. Just need to fix the rebase.

**Pull request merged**
