### PR TITLE
Update tls des

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
cc @lei-tang @louiscryan

### CODE REVIEW

**Review by kfaseela — APPROVED** [review]

**Comment by kfaseela** [comment]
Reference: https://github.com/istio/api/pull/2502#discussion_r1000916573

**Review by ericvn — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]
thanks

**Review by lei-tang — APPROVED** [review]
Thanks for the fix!

**Comment by kfaseela** [comment]
@hzxuzhonghu : you may want to check the gencheck failure

**Pull request merged**
