### PR TITLE
Add idle timeout

### PR DESCRIPTION
**Pull request by devincd**
add idle timeout to meshConfig
link istio/istio PR https://github.com/istio/istio/pull/11756

### CODE REVIEW

**Comment by rshriram** [comment]
We dont set HTTP keep alive. So, the Envoy issue related to this PR doesn't affect us right?

**Comment by devincd** [comment]
Yes, but when the envoy serves as the client connecting to the banckend, the default envoy is turn on keep-alive.At this time, the server side will actively disconnect due to the arrival of keep-alive timeout on the server side.

**Comment by costinm** [comment]
Does it even make sense to have this as a global setting ? I don't mind adding it to Sidecar or DestinationRule - but mesh config (in a normal install) can only be changed when doing an upgrade/restart, and it applies to the entire mesh. I can't imaging all servers in the mesh having same value.

**Comment by rshriram** [comment]
@devincd , if idle timeout is not set, its not enabled. So there is no keep alive timeout at all.

**Comment by geeknoid** [comment]
Closing due to inactivity.

**Pull request closed without merging**
