### PR TITLE
Vendor deps

### PR DESCRIPTION
**Pull request by rshriram**
Googleapi files..

### CODE REVIEW

**Comment by rshriram** [comment]
cc @costinm / @mandarjog .. need this in order for dep ensure in istio/istio to work.

**Comment by mandarjog** [comment]
related to https://github.com/istio/istio/pull/1354

**Comment by kyessenov** [comment]
there is a lot of unnecessary code here, but if it makes things compile, doesn't hurt :)

**Comment by ldemailly** [comment]
should this only checkin *.go ? 
how is the commit generated and how will we update it next ?

**Pull request closed without merging**
