### PR TITLE
Fix BoolValueForPB.GetValue allow nil

### PR DESCRIPTION
**Pull request by kebe7jun**
For: https://github.com/istio/api/issues/1938

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
You don't need this, protobuf.BoolValue already defines it

**Comment by kebe7jun** [comment]
> You don't need this, protobuf.BoolValue already defines it

See

https://github.com/istio/api/blob/a9c5294cac41c9089557ef1464f8353c5ef2b346/operator/v1alpha1/common.go#L60-L62

BoolValueForPB use struct `protobuf.BoolValue` not `*protobuf.BoolValue`, which makes nil(*BoolValueForPB).GetValue raise a nil pointer exception.

**Review by howardjohn — APPROVED** [review]

**Review by linsun — APPROVED** [review]

**Pull request merged**
