### PR TITLE
fix operator go struct tag

### PR DESCRIPTION
**Pull request by morvencao**
More context: https://github.com/istio/api/pull/1237#issue-365133001

### CODE REVIEW

**Comment by morvencao** [comment]
```
```

**Comment by morvencao** [comment]
```
IngressGateways      []*GatewaySpec     `protobuf:"bytes,40,rep,name=ingress_gateways,json=ingressGateways,proto3" json:"ingressGateways,omitempty"
```
Let's take the `IngressGateways` as an example, the tags for this field consists with two parts, `protobuf` and `json`; and also there is another `json` attribute in `protobuf` part. 

From our investigation, the `json` attribute in `protobuf`  tag is used for jsonpb lib to unmarshal/marshal, while `json` tag is used for json lib to unmarshal/marshal, which is used by kubernetes' go client AFAIK, so if we have go field with snake case： `json:"ingress_gateways,omitempty"`

```
IngressGateways      []*GatewaySpec     `protobuf:"bytes,40,rep,name=ingress_gateways,json=ingressGateways,proto3" json:"ingress_gateways,omitempty"
```
Then we have to write the IOP yaml like this:
```
components:
    ingress_gateways:
      - namespace: istio-system
```

**Comment by ostromart** [comment]
@morvencao are you saying the purpose of the PR is to be able to unmarshal using regular yaml/json unmarshalers (rather than jsonpb?). i think we are using jsonpb consistently throughout the codebase so is this a requirement or just to try to eliminate use of jsonpb?
i'm concerned about this change because in general we want to avoid messing around with the generated files unless we absolutely have to.
feel free to ping my during my evening to discuss further.

**Comment by morvencao** [comment]
We are using both the yaml/json unmarshalers and jsonpb unmarshaler.
For all the commands integrated with istioctl, we use jsonpb unmarshaler, while for controller, we need to retrieve and store the IOP instance from kube-apiserver with go-client lib, it will use the yaml/json unmarshalers bedefault, see: https://github.com/istio/istio/blob/master/operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go#L120
```
if err := r.client.Get(context.TODO(), reqNamespacedName, iop); err != nil {
...
}
```

**Comment by ostromart** [comment]
@morvencao we might as well in that case change everything to regular yaml unmarshal. it's dangerous to use two different unmarshal paths because we will lose test coverage. i've created https://github.com/istio/istio/issues/21039 to track.

**Comment by ostromart** [comment]
@morvencao this fix is needed in release-1.5, could you please cherrypick there?

**Comment by morvencao** [comment]
@ostromart https://github.com/istio/api/pull/1301

**Pull request merged**
