### PR TITLE
Add configuration fields for sidecar injection

### PR DESCRIPTION
**Pull request by ayj**

### CODE REVIEW

**Comment by ayj** [comment]
cc @kyessenov @andraxylia - This configuration will be consumed by k8s admission-controller/initializer and/or `kube-inject` to determine proper images to inject into end-user pod templates.

**Comment by kyessenov** [comment]
I'm not a supporter of embedding infrastructure-level concerns into proxy mesh config. If you think this is the way forward, I'll let other decide.

**Comment by ayj** [comment]
Alternative suggestions to make client-side `kube-inject` work short-term without istio.VERSION dependency? Or would you prefer continued use of sourcing istio.VERSION until `kube-inject` logic is moved server-side (pre-AC/initializer)?

**Comment by kyessenov** [comment]
Hardcode hub and tag to be :0.1 and image pull policy always. Then retag 0.1.x as 0.1 after each release.

**Pull request closed without merging**
