### PR TITLE
Fix typo, 'target' is not known 

### PR DESCRIPTION
**Pull request by pilhuhn**
target -> targets

Supersedes bad pr https://github.com/istio/istio.io/pull/2946

### CODE REVIEW

**Comment by pilhuhn** [comment]
Thank you @frankbu for guiding me. The `make proto-commit` had no (visible) effect. I guess because the definitions stayed the same and only the comment changed (?)

**Comment by frankbu** [comment]
@pilhuhn That's right, you only need to run `make proto-comit` if you change the actual message structure.

**Comment by hklai** [comment]
@pilhuhn/@frankbu master is actually locked. Please merge to release-1.1 before master is unlocked.

Also, perhaps it is worthwhile to cherry-pick this to release-1.1 as well?

**Pull request merged**
