### PR TITLE
update to individual owners - attempt to fix 2 approvers issue

### PR DESCRIPTION
**Pull request by linsun**
Discussed with @geeknoid on why our 2 approvers aren't working today.   @geeknoid suggested trying individual owners

### CODE REVIEW

**Comment by howardjohn** [comment]
What's the desired behavior? 2 TOC members or 1 TOC+1 other? The first is not possible as far as I know

**Comment by howardjohn** [comment]
and the second seemed to be working form what I've seen

**Comment by linsun** [comment]
In talking to @geeknoid @sdake my understanding is that TOC approved 2 approvers for API repo a while back, but it is not enforced today.

cc @istio/technical-oversight-committee

**Comment by howardjohn** [comment]
It does require 2 approvers, but only one has to be in the TOC. At least it used to a week or 2 ago

**Pull request merged**
