### PR TITLE
update host desc that a host can be defined using more than one vs

### PR DESCRIPTION
**Pull request by idouba**
the traffic properties of a host can be defined using more than one VirtualService
https://github.com/istio/istio/issues/12590

### CODE REVIEW

**Comment by linsun** [comment]
Thanks, LG to me.  Defer to @frankbu @rshriram to approve this.

**Comment by frankbu** [comment]
Thanks @idouba, but this needs to be sent to the `release-1.1` branch, so we can get it into the 1.1 docs.

**Comment by idouba** [comment]
@frankbu  release 1.1 pls refer to #873

**Pull request closed without merging**
