### PR TITLE
Update makefile for new docs plugin

### PR DESCRIPTION
**Pull request by howardjohn**
This PR is in parallel with https://github.com/istio/tools/pull/1393. This must be merged if that is, and will fail until its merged.

### CODE REVIEW

**Comment by howardjohn** [comment]
This is expected to fail until https://github.com/istio/common-files/pull/370 is merged. It would be good to have it approved so once the image updates it will not block other PRs

**Review by smawson — APPROVED** [review]

**Review by nrjpoddar — APPROVED** [review]
Can you attach an image or explain what/how it changes the rendered docs?

**Comment by howardjohn** [comment]
There is no changes to the rendered docs

**Review by brian-avery — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Pull request merged**
