### PR TITLE
replace quotes with backticks when referring to values

### PR DESCRIPTION
**Pull request by peterj**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by kfaseela** [comment]
should we cherrypick to 1.17 to fix this issue? https://github.com/istio/istio.io/issues/12808

**Comment by ericvn** [comment]
You'll likely want https://github.com/istio/api/pull/2658, https://github.com/istio/api/pull/2681 and maybe https://github.com/istio/api/pull/2683 as well.

**Pull request merged**
