### PR TITLE
update proto for WorkloadEntry since address is no longer required

### PR DESCRIPTION
**Pull request by GregHanson**
removed address as required field as part of https://github.com/istio/istio/issues/45161

### CODE REVIEW

**Comment by GregHanson** [comment]
cc @stevenctl

**Comment by GregHanson** [comment]
skipping release note here since one was already added as part of https://github.com/istio/istio/pull/45150/files#diff-f112bcf174a451762a9704c307f997d9ab618911e43a50da4a39c0ad9ae72785

**Review by howardjohn — APPROVED** [review]

**Review by stevenctl — APPROVED** [review]

**Pull request merged**
