### PR TITLE
Add missing quote in AuthenticationPolicy example.

### PR DESCRIPTION
**Pull request by JRBANCEL**
Ran `make clean gen` and `make proto-commit`.

### CODE REVIEW

**Review by smawson — COMMENTED** [review]
Why are there so many changes in proto.lock?

**Comment by JRBANCEL** [comment]
> Why are there so many changes in proto.lock?

No idea. Also, after rebasing and running `make clean gen` and `make proto-commit`, a ton of generated `.go` files have been modified as well :neutral_face:

**Comment by JRBANCEL** [comment]
What am I doing wrong?

I edit `security/v1beta1/request_authentication.pb.go`, run `make clean gen` and `make proto-commit` and it generates this PR. `gencheck_api` fails asking to run `make gen`.

**Comment by JRBANCEL** [comment]
@smawson I finally managed to find out which files generated by `make clean gen` and `make proto-commit` should be ignored to make `gencheck_pai` succeed.

**Comment by smawson** [comment]
Please remove anything unrelated to the change you're making. If generated files are out of date those should be updated in a separate PR, so the two issues are conflated.

This is good practice to get into so you can selectively revert as needed without reverting unrelated things.

**Comment by JRBANCEL** [comment]
I am very aware of this practice, but in this case what am I supposed to do?

>  If generated files are out of date those should be updated in a separate PR

That's not the case here. Executing `make clean gen && make proto-commit` on `master` branch doesn't modify any file.

So, I simply edit `security/v1beta1/request_authentication.proto`, but then `make clean gen && make proto-commit` updates a ton of files:

```
▶ git status
        modified:   analysis/v1alpha1/message_json.gen.go
        modified:   authentication/v1alpha1/policy_json.gen.go
        modified:   meta/v1alpha1/status_json.gen.go
        modified:   networking/v1alpha3/destination_rule_json.gen.go
        modified:   networking/v1alpha3/envoy_filter_json.gen.go
        modified:   networking/v1alpha3/gateway_json.gen.go
        modified:   networking/v1alpha3/service_entry_json.gen.go
        modified:   networking/v1alpha3/sidecar_json.gen.go
        modified:   networking/v1alpha3/virtual_service_json.gen.go
        modified:   networking/v1alpha3/workload_entry_json.gen.go
        modified:   networking/v1alpha3/workload_group_json.gen.go
        modified:   networking/v1beta1/destination_rule_json.gen.go
        modified:   networking/v1beta1/gateway_json.gen.go
        modified:   networking/v1beta1/service_entry_json.gen.go
        modified:   networking/v1beta1/sidecar_json.gen.go
        modified:   networking/v1beta1/virtual_service_json.gen.go
        modified:   networking/v1beta1/workload_entry_json.gen.go
        modified:   proto.lock
        modified:   security/v1beta1/authorization_policy_json.gen.go
        modified:   security/v1beta1/jwt_json.gen.go
        modified:   security/v1beta1/peer_authentication_json.gen.go
        modified:   security/v1beta1/request_authentication.pb.go
        modified:   security/v1beta1/request_authentication.pb.html
        modified:   security/v1beta1/request_authentication.proto
        modified:   security/v1beta1/request_authentication_json.gen.go
        modified:   type/v1beta1/selector_json.gen.go
```

If I check-in only what is supposedly related to the change:

```
        modified:   security/v1beta1/request_authentication.pb.go
        modified:   security/v1beta1/request_authentication.pb.html
        modified:   security/v1beta1/request_authentication.proto
        modified:   security/v1beta1/request_authentication_json.gen.go
```

Then, the presubmit `gencheck_api` fails and the PR can't be merged.
The current state of the PR passes the pre-submit.

**Comment by smawson** [comment]
Wow that is bizarre. Anyone with more experience with our code generator that can help out here? Why would this comment change result in the changes to allow unknown fields?

**Comment by JRBANCEL** [comment]
> Wow that is bizarre. Anyone with more experience with our code generator that can help out here? Why would this comment change result in the changes to allow unknown fields?

I deleted my comment. It was fixed by https://github.com/istio/api/pull/1677.

After rebasing my change, it is cleaner.

That being said, it shouldn't be possible to end up in this state.

**Review by smawson — APPROVED** [review]
That looks better, sorry about the pain.

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
