### PR TITLE
add API for ALPN filter

### PR DESCRIPTION
**Pull request by yxue**

### CODE REVIEW

**Comment by kyessenov** [comment]
FYI, do not use these gogo protos in an xDS server. I'm trying to delete them unsuccessfully from here https://github.com/istio/api/pull/1110. You need to use standard golang protos.

**Comment by yxue** [comment]
> FYI, do not use these gogo protos in an xDS server. I'm trying to delete them unsuccessfully from here #1110. You need to use standard golang protos.

Are we going to maintain two proto files? One in istio/api, one in istio/istio.

**Comment by yxue** [comment]
Are we going to maintain two proto files? One in istio/api and another one in istio/istio

**Comment by kyessenov** [comment]
The proto can stay here.

**Pull request merged**
