### PR TITLE
Make the numbering of message fields consecutive

### PR DESCRIPTION
**Pull request by lei-tang**
Make the numbering of the message fields in the authentication policy consecutive.

### CODE REVIEW

**Comment by wora** [comment]
Are you sure these fields are not being used? No breaking change should be allowed for Istio APIs.

**Comment by lei-tang** [comment]
These fields are not being used (policy.proto is for the Istio authentication policy, which is a work in progress).

**Comment by diemtvu** [comment]
lgtm, though I don't think this clean up is necessary.

**Comment by douglas-reid** [comment]
Does this PR will need python generation updates now?

**Comment by lei-tang** [comment]
Just did a search for "*.py" files under this repo and have not found any "*.py" files generated for the proto files. If python code is needed, please let me know.

**Comment by douglas-reid** [comment]
https://github.com/istio/api/blob/master/python/istio_api/authentication/v1alpha1/policy_pb2.py ?

**Comment by lei-tang** [comment]
Thanks! Python update has been added.

**Comment by wora** [comment]
I recommend we never renumber a field unless it is marked as not ready, do not use. There is very little value to do it. Sooner or later a mistake would cause a major outage somewhere else.

**Comment by geeknoid** [comment]
Should we close this PR?

@diemtvu

**Pull request closed without merging**
