### PR TITLE
Use RE2 instead of ECMAscript regex-based match

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio/issues/32598

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by shamsher31** [comment]
@linsun PTAL.

**Comment by shamsher31** [comment]
@nrjpoddar PTAL.

**Comment by shamsher31** [comment]
cc: @linsun @nrjpoddar

**Review by nrjpoddar — COMMENTED** [review]
What's the impact of this change on existing user resources? Is there any guidance to help them migrate from ECMA to RE2?

**Comment by howardjohn** [comment]
> What's the impact of this change on existing user resources? Is there any guidance to help them migrate from ECMA to RE2?

It was always RE2 I believe. If not, it was changed long ago in 1.4 to RE2 (when they moved to safe_regex). So this is just a docs update, not a behavioral change

**Review by nrjpoddar — APPROVED** [review]

**Pull request merged**
