### PR TITLE
Adding creation_timestamp to ServiceEntry proto

### PR DESCRIPTION
**Pull request by nmittler**
This is to support an on-going PR: https://github.com/istio/istio/pull/6993

### CODE REVIEW

**Comment by nmittler** [comment]
FYI @rshriram @costinm

**Comment by nmittler** [comment]
/hold

I'm actually not certain we need this.  Will follow up shortly.

**Comment by kyessenov** [comment]
Why can't you use CRD timestamp? It's going to be super confusing to have creation timestamps within creation timestamps.

**Comment by rshriram** [comment]
Yes. CRD timestamps should be sufficient. Closing for the moment

**Pull request closed without merging**
