### PR TITLE
Add max_concurrent_streams definition to DestinationRule

### PR DESCRIPTION
**Pull request by jaellio**
Part of https://github.com/istio/istio/issues/47166

**NOTE** This also impacts the sidecar resource which has a connectionPoolSetting field.

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Since we have `MaxRequestsPerConnection`, which is similar, why do we need another field?

**Comment by keithmattix** [comment]
I personally would prefer to use a setting whose existence and behavior is ~guaranteed by the HTTP/2 spec rather than a proxy specific implementation.

**Comment by jaellio** [comment]
Even though setting `max_requests_per_connection` for http/2 connections results in a similar outcome to setting `max_concurrent_streams`, adding support for `max_concurrent_streams` introduces minimal complexity and matches the user's expectation of settings available for http/2 connections.

**Comment by hzxuzhonghu** [comment]
It is already confusing since we donot distinguish http1.1 and http2 connection pool settings,  I feel this will make things worse

**Comment by jaellio** [comment]
How will we handle new HTTP settings that are only applicable to HTTP1 or HTTP2, but not both?

**Review by howardjohn — APPROVED** [review]

**Comment by linsun** [comment]
@hzxuzhonghu do you have a better way to do this?

@jaellio the change LGTM, ready to approve if @hzxuzhonghu doesn't have strong objections to it.

**Review by hzxuzhonghu — CHANGES_REQUESTED** [review]
I donot think `MaxConcurrentStreams` should be in tcp settings.
 If we want to explicitly distinguish it from HTTP setting, we can add it in http2Settings

**Comment by keithmattix** [comment]
> I donot think `MaxConcurrentStreams` should be in tcp settings.
> 
>  If we want to explicitly distinguish it from HTTP setting, we can add it in http2Settings

This is a really good catch that I missed; indeed max_concurrent_streams does not belong in tcp settings. Good call out @hzxuzhonghu

**Comment by linsun** [comment]
Great catch @hzxuzhonghu!  +1

**Comment by jaellio** [comment]
> I donot think `MaxConcurrentStreams` should be in tcp settings. If we want to explicitly distinguish it from HTTP setting, we can add it in http2Settings

Yes, thank you, I missed that! Updated!

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by ramaraochavali** [comment]
Sorry for the late comment. To make this more clear that it only applies to http2, should we call it `http2_max_concurrent_streams` similar to how we distinguish other settings like `http2_max_requests` and `http1_max_pending_requests` . Ideally we should have different settings for http1/http2/http3 - but it is too late to change them

**Comment by jaellio** [comment]
> Sorry for the late comment. To make this more clear that it only applies to http2, should we call it `http2_max_concurrent_streams` similar to how we distinguish other settings like `http2_max_requests` and `http1_max_pending_requests` . Ideally, we should have different settings for http1/http2/http3 - but it is too late to change them

@ramaraochavali good call out. I am fine with making this update, but I was confused about the descriptions of the fields that are prefixed with `http1` or `http2`. The descriptions for all of these fields include: "Please note that this is applicable to both HTTP/1.1 and HTTP2." https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-HTTPSettings I understand that this field is specific to http2, but I didn't want to make it more confusing.

**Comment by ramaraochavali** [comment]
I think those are different and this specific field is only for http2. I am OK with moving as is

**Pull request merged**
