### PR TITLE
Even with permissive mode, the TLS require client cert

### PR DESCRIPTION
**Pull request by sureshvis**
Even with permissive mode, the filter chain adds "require_client_certificate": true" and required you to pass client cert.

@rshriram pls review

### CODE REVIEW

**Comment by incfly** [comment]
So this is just a doc change right?

**Comment by sureshvis** [comment]
yes

**Comment by mandarjog** [comment]
@jasonwzm  please look at this error.
```panic: runtime error: slice bounds out of range [:-1]
goroutine 1 [running]:
main.(*builder).genCRD(0xc000680460)
	/tmp/go/pkg/mod/istio.io/tools@v0.0.0-20191126072843-2e858b7fde8d/cmd/cue-gen/genoapi.go:414 +0x935
main.main()
	/tmp/go/pkg/mod/istio.io/tools@v0.0.0-20191126072843-2e858b7fde8d/cmd/cue-gen/genoapi.go:300 +0xbd3
Makefile.core.mk:466: recipe for target 'kubernetes/customresourcedefinitions.gen.yaml' failed
make: *** [kubernetes/customresourcedefinitions.gen.yaml] Error 2
```

**Comment by jasonwzm** [comment]
Can you rebase the branch with master and try again?

**Comment by howardjohn** [comment]
/retest

you don't need to rebase

**Pull request merged**
