### PR TITLE
ns of egress gateway should be istio-system in the context

### PR DESCRIPTION
**Pull request by idouba**
ns of egress gateway should be istio-system in the context

### CODE REVIEW

**Comment by linsun** [comment]
This is not strictly necessary. you can put ingress and egress onto its own namespace.

**Comment by idouba** [comment]
@linsun yes, Gateway can be in their own ns .
In the example context
```
  http:
  - match:
    - port: 80
      gateways:
      - mesh
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
```
vs using the egress-gateway in **istio-system**.

**Pull request merged**
