### PR TITLE
Add CRD labels to WorkloadGroup

### PR DESCRIPTION
**Pull request by jasonwzm**
Fix of api for https://github.com/istio/istio/issues/30312

### CODE REVIEW

**Comment by tmshort** [comment]
Are the manifest files automatically updated?

**Review by howardjohn — APPROVED** [review]
I think the labels here are probably not great (app=istio-pilot is not used anywhere else), but its consistent with other CRDs which is more important. LGTM

**Review by smawson — APPROVED** [review]

**Comment by jasonwzm** [comment]
@tmshort After this is merged, we will manually update the istio/istio repo.

**Comment by howardjohn** [comment]
It will auto update (if it works right)

**Pull request merged**
