### PR TITLE
Unhide the targetRef docs

### LINKED ISSUE #2978: Add targetRef Docs
**Describe the feature request**
Add docs for targetRef once the recent targetRef changes have been cherrypicked into 1.20.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

### PR DESCRIPTION
**Pull request by MorrisLaw**
Unhide the targetRef documentation.

Closes #2978

### CODE REVIEW

**Comment by ericvn** [comment]
If we want this in the 1.20 docs when they are released, we will need to also cherrypick this to 1.20.

**Comment by MorrisLaw** [comment]
@ericvn that's right, I forgot to add the label. Thank you!

**Review by keithmattix — APPROVED** [review]

**Review by howardjohn — COMMENTED** [review]
I am a bit worried about documenting this (which goes directly to docs in our v1 APIs) when its only implemented for waypoints? Especially as its not listed as "only for waypoints" either?

is it premature to do this?

**Comment by keithmattix** [comment]
> I am a bit worried about documenting this (which goes directly to docs in our v1 APIs) when its only implemented for waypoints? Especially as its not listed as "only for waypoints" either?
> 
> is it premature to do this?

It's not only for waypoints? `targetRef` can be used for any Gateway API gateway, not just waypoints

**Review by whitneygriffith — APPROVED** [review]

**Review by linsun — COMMENTED** [review]
A little worried about unhide this for 1.20.x as well

**Comment by keithmattix** [comment]
@linsun could you confirm which API you're talking about? I believe all of the changes for targetRef resources have been merged and released in 1.20

**Comment by peterj** [comment]
I was going through this today and also noticed the `$hide_from_docs` in the proto, even though the release notes mentioned it as implemented.

**Comment by linsun** [comment]
> @linsun could you confirm which API you're talking about? I believe all of the changes for targetRef resources have been merged and released in 1.20

Sorry just saw this - in yesterday's ambient meeting, I asked @louiscryan and @howardjohn for an update on authz policy which they mentioned they would share a draft by end of this week. I was referring to that may change where we are going with targetRef for authz policy.

**Comment by keithmattix** [comment]
> > @linsun could you confirm which API you're talking about? I believe all of the changes for targetRef resources have been merged and released in 1.20
> 
> Sorry just saw this - in yesterday's ambient meeting, I asked @louiscryan and @howardjohn for an update on authz policy which they mentioned they would share a draft by end of this week. I was referring to that may change where we are going with targetRef for authz policy.

Ah I see what you mean. In my opinion, the targetRef field has already been added to AuthorizationPolicy and the release notes for 1.20 refers to the new fields. It would make sense to have associated docs for it right?

**Comment by hanxiaop** [comment]
> > > @linsun could you confirm which API you're talking about? I believe all of the changes for targetRef resources have been merged and released in 1.20
> > 
> > 
> > Sorry just saw this - in yesterday's ambient meeting, I asked @louiscryan and @howardjohn for an update on authz policy which they mentioned they would share a draft by end of this week. I was referring to that may change where we are going with targetRef for authz policy.
> 
> Ah I see what you mean. In my opinion, the targetRef field has already been added to AuthorizationPolicy and the release notes for 1.20 refers to the new fields. It would make sense to have associated docs for it right?

When I generate the release notes, I find that there are ~3 notes related to the `targetRef`, which I assume is a new feature in 1.20. I think it's not easy for RMs to determine what should or should not be included, may still be a problem in the future.

**Comment by linsun** [comment]
> > > > @linsun could you confirm which API you're talking about? I believe all of the changes for targetRef resources have been merged and released in 1.20
> > > 
> > > 
> > > Sorry just saw this - in yesterday's ambient meeting, I asked @louiscryan and @howardjohn for an update on authz policy which they mentioned they would share a draft by end of this week. I was referring to that may change where we are going with targetRef for authz policy.
> > 
> > 
> > Ah I see what you mean. In my opinion, the targetRef field has already been added to AuthorizationPolicy and the release notes for 1.20 refers to the new fields. It would make sense to have associated docs for it right?
> 
> When I generate the release notes, I find that there are ~3 notes related to the `targetRef`, which I assume is a new feature in 1.20. I think it's not easy for RMs to determine what should or should not be included, may still be a problem in the future.

Understood - sorry to make this not easy for everyone. We don't often churn design like this in Istio...My main worry is we tell users to do one way in 1.20, and another way in 1.21 or 1.22 given we already know the change is coming.

**Comment by keithmattix** [comment]
@louiscryan @howardjohn can either of you give a heads up on if the authz policy doc you're working on will modify the binding mechanism for adding policies to the waypoint?

**Comment by MorrisLaw** [comment]
> @louiscryan @howardjohn can either of you give a heads up on if the authz policy doc you're working on will modify the binding mechanism for adding policies to the waypoint?

Any update on this that you're aware of @keithmattix ?

**Comment by keithmattix** [comment]
@howardjohn agreed - are there any other hesitations from merging this PR (which btw just documents targetRef for k8s gateway and waypoint use-cases)

**Comment by linsun** [comment]
I have no further concern based on most recent docs.

**Pull request merged**
