### PR TITLE
Add v1beta1 for Networking APIs

### PR DESCRIPTION
**Pull request by jasonwzm**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
One question: how should we support two versions simultaneously? CRD conversion?

**Comment by jasonwzm** [comment]
> One question: how should we support two versions simultaneously? CRD conversion?

For v1beta1 and 1.5, they are the same schema with v1alpha3 APIs. In 1.6, we will use API conversion.

**Comment by hzxuzhonghu** [comment]
>For v1beta1 and 1.5, they are the same schema with v1alpha3 APIs.
But we can not get v1alpha resource with v1beta1 client.

>In 1.6, we will use API conversion.

It seems this is the only feasible solution

**Comment by jasonwzm** [comment]
> > For v1beta1 and 1.5, they are the same schema with v1alpha3 APIs.
> 
> But we can not get v1alpha resource with v1beta1 client.
> 
Since they are the same schema, you are able to get the resource with either version.

**Comment by hzxuzhonghu** [comment]
ah, good. Long time no tracing it. https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions

**Pull request merged**
