### PR TITLE
cherry-pick of #1085

### PR DESCRIPTION
**Pull request by kyessenov**
Cherrypick of #1085.

### CODE REVIEW

**Comment by rlenglet** [comment]
@kyessenov please add an entry for this PR into the [1.3.7 release note draft](https://github.com/istio/istio/wiki/Release-Note-1.3.7-Draft).

**Comment by kyessenov** [comment]
/retest
Because the build is eventually consistent.

**Comment by kyessenov** [comment]
Can you merge please, so I can propagate the SHA?

**Comment by rlenglet** [comment]
I can't force-merge.
@brian-avery can you please approve this? istio/api requires 2 approvals.

**Pull request merged**
