### PR TITLE
Hide ServiceEntry.Location from docs

### PR DESCRIPTION
**Pull request by jwendell**
As it's not used anymore.

### CODE REVIEW

**Comment by jwendell** [comment]
I can also nuke all references to this field on istio/istio, as part of https://github.com/istio/istio/issues/17157, what do you think?

**Comment by howardjohn** [comment]
We can keep it around forever as hidden -- is that better than mentioning
its not used? I am fine with either one, I think we shouldn't actually
remove it though

**Comment by rshriram** [comment]
that also works. just dont remove it yet

**Comment by jwendell** [comment]
@rshriram done.

**Comment by rshriram** [comment]
Given how we have started using this heavily for auto mTLS, i dont think we can hide this anymre

**Comment by jwendell** [comment]
ok, closing then.

**Pull request closed without merging**
