### PR TITLE
Clean up unused field

### PR DESCRIPTION
**Pull request by wattli**

### CODE REVIEW

**Comment by wattli** [comment]
@diemtvu @costinm please take a look.

**Comment by diemtvu** [comment]
/hold
Let's hold this change. Quanjie may need to use this for dark launch. She will test it out and see if it's usable.

**Comment by wattli** [comment]
@geeknoid , can you help to review ?

**Comment by quanjielin** [comment]
Subset is useful if we want to support authN policy on subset of proxies inside mesh(I have a [prototype PR](https://github.com/istio/istio/issues/5486) for this); if we want to support that, we may have to hold this PR.

**Comment by wattli** [comment]
@diemtvu , do we want to support auth policy on subset as @quanjielin mentioned?

**Comment by wattli** [comment]
Chatted with Quanjie and Diem offline, we are good for this PR to be merged.

@geeknoid , the presubmit takes quite a long time, do you know what happens or can you help to merge? Thanks

**Pull request merged**
