### PR TITLE
add mixerclient config to istio.io reference docs

### PR DESCRIPTION
**Pull request by ayj**
fixes https://github.com/istio/istio.io/issues/2851

### CODE REVIEW

**Comment by ayj** [comment]
Here are the other APIs with missing location tags:

```
No 'location:' tag in mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.pb.html, skipping
No 'location:' tag in mcp/v1alpha1/istio.mcp.v1alpha1.pb.html, skipping
No 'location:' tag in mixer/adapter/bypass/config/adapter.bypass.config.pb.html, skipping
No 'location:' tag in mixer/adapter/rbac/config/adapter.rbac.config.pb.html, skipping
No 'location:' tag in mixer/test/spyAdapter/template/quota/sampleQuota.pb.html, skipping
No 'location:' tag in security/proto/providers/google/google.security.istioca.v1alpha1.pb.html, skipping
No 'location:' tag in security/proto/istio.v1.auth.pb.html, skipping
```

cc @diemtvu @wattli (security)
cc @kyessenov (mixer adapter)

**Comment by kyessenov** [comment]
I'm confused. Are these APIs published in mixer published? Some of them are testing ones and not meant to be published.

**Comment by ayj** [comment]
None of the API I listed with "no location" are published on istio.io. We don't need publish the bypass or test spyAdapter. However, I'm not sure about the istio.mixer.adapter.model.v1beta1 or the security ones.

**Comment by geeknoid** [comment]
@ayj Can we get this merged?

**Pull request merged**
