### PR TITLE
Update go to 1.22

### PR DESCRIPTION
**Pull request by jaellio**
https://github.com/istio/istio/issues/48443

### CODE REVIEW

**Comment by jaellio** [comment]
Should the go version in `tests/go.mod` also be updated to 1.22.1?

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
> Should the go version in `tests/go.mod` also be updated to 1.22.1?

:+1: I think its good to keep them in sync

**Review by zirain — APPROVED** [review]

**Pull request merged**
