### PR TITLE
update annotations and labels page

### PR DESCRIPTION
**Pull request by zirain**
xref: https://github.com/istio/api/pull/3043

### CODE REVIEW

**Comment by zirain** [comment]
wait https://github.com/istio/test-infra/pull/5155

**Review by hanxiaop — APPROVED** [review]
Approved since it's a doc enhancement. https://github.com/istio/istio/wiki/Istio-Release-1.20#how-do-i-get-my-changes-into-the-release

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
