### PR TITLE
[Manual Cherry-Pick] Fix quantity and lock down others to a more specific type (#1567)

### PR DESCRIPTION
**Pull request by liamawhite**
* Fix quantity and lock down others to correct IntOrString

Signed-off-by: Liam White <liam@tetrate.io>

* fix imports

Signed-off-by: Liam White <liam@tetrate.io>

### CODE REVIEW

**Comment by jwendell** [comment]
@liamawhite are those tests supposed to fail?

**Comment by liamawhite** [comment]
It seems to be failing on a merge conflict with master. This is the same failure that required me to do a manual cherry-pick. So ¯\_(ツ)_/¯?

**Comment by jwendell** [comment]
api repo is too complicated to me... perhaps this should get merged in master first? https://github.com/istio/api/pull/1551

**Comment by liamawhite** [comment]
I think its probably safe to merge otherwise those tests would be required?

**Comment by jwendell** [comment]
Could some api expert advice here?
@rshriram @duderino @louiscryan @dcberg @smawson @linsun

**Comment by jwendell** [comment]
oh, I know what's going on here. The failed tests are tests from master. Not sure why they were triggered in this PR. Have you changed the branch target of this PR after it was created?

**Pull request merged**
